package CollectionsFramework;

import java.util.*;

class Contact{
    String name, phone, email;
    Contact(String name, String phone, String email){
        this.name = name;
        this.phone = phone;
        this.email = email;
    }
    @Override
    public String toString() {
        return name + " | " + phone + " | " + email;
    }
}

class ContactManagementSystem {

    // contactId -> [name, phone, email]
    Map<Integer, Contact> contacts;

    public ContactManagementSystem() {
        contacts = new HashMap<>();
    }

    // Add a new contact or update if exists
    public void addContact(int contactId, String name,
                           String phone, String email) {
        Contact contact = new Contact(name, phone, email);
        contacts.put(contactId, contact);
    }

    // Remove contact completely
    public void removeContact(int contactId) {
        if(!contacts.containsKey(contactId))
            throw new NoSuchElementException("Contact not found!");
        contacts.remove(contactId);
    }

    // Update contact details
    public void updateContact(int contactId, String name,
                              String phone, String email) {
        if(!contacts.containsKey(contactId))
            throw new NoSuchElementException("Contact not found!");
        Contact contact = new Contact(name, phone, email); //create a new contact object and put that
        contacts.put(contactId, contact);
    }

    // Get single contact
    public Contact getContact(int contactId) {
        if(!contacts.containsKey(contactId))
            throw new NoSuchElementException("Contact not found!");
        else
            return contacts.get(contactId);
    }

    // Get all contacts
    public List<Contact> getAllContacts() {
        return new ArrayList<>(contacts.values());
    }


    //testing the code; not asked for in the question.. but for sanity checks. *tests generated by AI.*
    public static void main(String[] args) {
        ContactManagementSystem cms = new ContactManagementSystem();

        // Add contacts
        cms.addContact(1, "Alice", "1234567890", "alice@gmail.com");
        cms.addContact(2, "Bob", "9876543210", "bob@gmail.com");
        cms.addContact(3, "Charlie", "5555555555", "charlie@gmail.com");

        System.out.println("All Contacts After Adding:");
        for (Contact c : cms.getAllContacts()) {
            System.out.println(c);
        }

        // Get one contact
        System.out.println("\nGet Contact with ID 2:");
        System.out.println(cms.getContact(2));

        // Update contact
        cms.updateContact(2, "Bob Updated", "1111111111", "bobupdated@gmail.com");
        System.out.println("\nAfter Updating Contact ID 2:");
        System.out.println(cms.getContact(2));

        // Remove contact
        cms.removeContact(1);
        System.out.println("\nAfter Removing Contact ID 1:");
        for (Contact c : cms.getAllContacts()) {
            System.out.println(c);
        }

        // Try to access removed contact (will throw exception)
        System.out.println("\nTrying to get removed contact ID 1:");
        try {
            System.out.println(cms.getContact(1));
        } catch (NoSuchElementException e) {
            System.out.println("Exception caught: " + e.getMessage());
        }
    }

}

